"""Compatibility import surface for the Module 8 feature engine."""

from hct_backend.features import (
    DERIVED_MTF_PROVENANCE,
    FEATURE_ALGORITHM_VERSION,
    FEATURE_AUTHORITY_VERSION,
    FEATURE_DECIMAL_POLICY_VERSION,
    RECURSIVE_STATE_VERSION,
    AlignedWindowEvidence,
    FeatureAuthorityEvidence,
    FeatureAxisRestriction,
    FeatureDefinition,
    FeatureError,
    FeatureEvaluationError,
    FeatureRegistry,
    FeatureRegistryError,
    FeatureSample,
    FeatureSnapshot,
    FeatureValidity,
    FeatureValue,
    FeatureVersion,
    RecursiveAccumulatorState,
    align_candles,
    align_closed_1m_candles,
    evaluate_feature,
    evaluate_feature_series,
    evaluate_snapshot,
    restore_recursive_state,
)

__all__ = [
    "AlignedWindowEvidence",
    "DERIVED_MTF_PROVENANCE",
    "FEATURE_ALGORITHM_VERSION",
    "FEATURE_AUTHORITY_VERSION",
    "FEATURE_DECIMAL_POLICY_VERSION",
    "FeatureAuthorityEvidence",
    "FeatureAxisRestriction",
    "FeatureDefinition",
    "FeatureError",
    "FeatureEvaluationError",
    "FeatureRegistry",
    "FeatureRegistryError",
    "FeatureSample",
    "FeatureSnapshot",
    "FeatureValidity",
    "FeatureValue",
    "FeatureVersion",
    "RECURSIVE_STATE_VERSION",
    "RecursiveAccumulatorState",
    "align_candles",
    "align_closed_1m_candles",
    "evaluate_feature",
    "evaluate_feature_series",
    "evaluate_snapshot",
    "restore_recursive_state",
]
