"""Generated from packages/contracts/openapi.json; do not edit."""
# ruff: noqa: E501

CONTRACT_SHA256 = "aeebefe1610c3c4664d453aca9c33aa8395172f50a5477b7ec2e0e7eaeb95289"
SCHEMAS = {'AuditEnvelope': {'additionalProperties': False,
                   'properties': {'environment': {'$ref': '#/components/schemas/Environment'},
                                  'event_id': {'$ref': '#/components/schemas/EnvironmentScopedId'},
                                  'event_type': {'maxLength': 64,
                                                 'minLength': 2,
                                                 'pattern': '^[A-Z][A-Z0-9_.-]{1,63}$',
                                                 'type': 'string'},
                                  'occurred_at': {'format': 'date-time',
                                                  'type': 'string'},
                                  'payload_hash': {'pattern': '^[0-9a-f]{64}$',
                                                   'type': 'string'}},
                   'required': ['event_id',
                                'environment',
                                'event_type',
                                'payload_hash',
                                'occurred_at'],
                   'type': 'object'},
 'Environment': {'enum': ['LIVE', 'PAPER', 'SHADOW', 'REPLAY'],
                 'type': 'string'},
 'EnvironmentScopedId': {'additionalProperties': False,
                         'properties': {'environment': {'$ref': '#/components/schemas/Environment'},
                                        'kind': {'$ref': '#/components/schemas/IdentityKind'},
                                        'value': {'maxLength': 64,
                                                  'minLength': 1,
                                                  'pattern': '^[a-z0-9][a-z0-9._-]{0,63}$',
                                                  'type': 'string'}},
                         'required': ['kind', 'environment', 'value'],
                         'type': 'object'},
 'ErrorEnvelope': {'additionalProperties': False,
                   'properties': {'code': {'enum': ['INVALID_REQUEST',
                                                    'NOT_READY',
                                                    'INTERNAL'],
                                           'type': 'string'},
                                  'message': {'maxLength': 256,
                                              'minLength': 1,
                                              'type': 'string'},
                                  'request_id': {'anyOf': [{'maxLength': 64,
                                                            'type': 'string'},
                                                           {'type': 'null'}]}},
                   'required': ['code', 'message'],
                   'type': 'object'},
 'EvidenceEnvelope': {'additionalProperties': False,
                      'properties': {'environment': {'$ref': '#/components/schemas/Environment'},
                                     'evidence_id': {'$ref': '#/components/schemas/EnvironmentScopedId'},
                                     'evidence_type': {'maxLength': 64,
                                                       'minLength': 2,
                                                       'pattern': '^[A-Z][A-Z0-9_.-]{1,63}$',
                                                       'type': 'string'},
                                     'payload_hash': {'pattern': '^[0-9a-f]{64}$',
                                                      'type': 'string'}},
                      'required': ['evidence_id',
                                   'environment',
                                   'evidence_type',
                                   'payload_hash'],
                      'type': 'object'},
 'HealthResponse': {'additionalProperties': False,
                    'properties': {'service': {'const': 'hct-backend',
                                               'type': 'string'},
                                   'status': {'const': 'ok',
                                              'type': 'string'}},
                    'required': ['service', 'status'],
                    'type': 'object'},
 'IdentityKind': {'enum': ['SERVICE',
                           'RELEASE',
                           'CONFIG',
                           'AUDIT',
                           'EVIDENCE',
                           'EXCHANGE',
                           'INSTRUMENT',
                           'CAPABILITY_SNAPSHOT',
                           'REFERENCE_SNAPSHOT'],
                  'type': 'string'},
 'ReadinessResponse': {'additionalProperties': False,
                       'properties': {'checks': {'additionalProperties': {'const': 'ready',
                                                                          'type': 'string'},
                                                 'type': 'object'},
                                      'service': {'const': 'hct-backend',
                                                  'type': 'string'},
                                      'status': {'const': 'ready',
                                                 'type': 'string'}},
                       'required': ['service', 'status', 'checks'],
                       'type': 'object'},
 'StableId': {'additionalProperties': False,
              'properties': {'kind': {'$ref': '#/components/schemas/IdentityKind'},
                             'value': {'maxLength': 64,
                                       'minLength': 1,
                                       'pattern': '^[a-z0-9][a-z0-9._-]{0,63}$',
                                       'type': 'string'}},
              'required': ['kind', 'value'],
              'type': 'object'},
 'VersionResponse': {'additionalProperties': False,
                     'properties': {'contract_sha256': {'pattern': '^[0-9a-f]{64}$',
                                                        'type': 'string'},
                                    'release': {'$ref': '#/components/schemas/StableId'},
                                    'service': {'const': 'hct-backend',
                                                'type': 'string'}},
                     'required': ['service',
                                  'release',
                                  'contract_sha256'],
                     'type': 'object'}}
ENVIRONMENTS = ('LIVE', 'PAPER', 'SHADOW', 'REPLAY')
IDENTITY_KINDS = ('SERVICE', 'RELEASE', 'CONFIG', 'AUDIT', 'EVIDENCE', 'EXCHANGE', 'INSTRUMENT', 'CAPABILITY_SNAPSHOT', 'REFERENCE_SNAPSHOT')
ERROR_CODES = ('INVALID_REQUEST', 'NOT_READY', 'INTERNAL')
SAFE_ENDPOINTS = ('/health', '/ready', '/version')
ID_VALUE_PATTERN = r"^[a-z0-9][a-z0-9._-]{0,63}$"
EVENT_TYPE_PATTERN = r"^[A-Z][A-Z0-9_.-]{1,63}$"
HASH_PATTERN = r"^[0-9a-f]{64}$"
