"""Compatibility import surface for the Module 9 pattern engine."""

from hct_backend.patterns import (
    LONG_BODY_MIN,
    PATTERN_ALGORITHM_VERSION,
    PATTERN_ALLOWLIST,
    PATTERN_DECIMAL_POLICY_VERSION,
    PATTERN_DEFINITION_VERSION,
    PATTERN_EVIDENCE_VERSION,
    PATTERN_FINGERPRINT_VERSION,
    SMALL_BODY_MAX,
    PatternConstituent,
    PatternDefinition,
    PatternDirection,
    PatternError,
    PatternEvaluationError,
    PatternEvidence,
    PatternMatchState,
    PatternRegistry,
    PatternRegistryError,
    PatternValidity,
    PatternVersion,
    canonical_evidence_order,
    evaluate_pattern,
    evaluate_patterns,
)

__all__ = [
    "LONG_BODY_MIN",
    "PATTERN_ALGORITHM_VERSION",
    "PATTERN_ALLOWLIST",
    "PATTERN_DEFINITION_VERSION",
    "PATTERN_DECIMAL_POLICY_VERSION",
    "PATTERN_EVIDENCE_VERSION",
    "PATTERN_FINGERPRINT_VERSION",
    "SMALL_BODY_MAX",
    "PatternConstituent",
    "PatternDefinition",
    "PatternDirection",
    "PatternError",
    "PatternEvaluationError",
    "PatternEvidence",
    "PatternMatchState",
    "PatternRegistry",
    "PatternRegistryError",
    "PatternValidity",
    "PatternVersion",
    "canonical_evidence_order",
    "evaluate_pattern",
    "evaluate_patterns",
]
